name: director
listen: "{{HOST|default('0.0.0.0')}}:{{PORT|default(8080)}}"
env: "{{ENV}}"
redis_dsn: "{{REDIS_DSN|default('redis://redis:6379')}}"
startup: {{ RUN_CONTAINERS.split(',') }}

images:
  - name: rst/band-base-py
    path: "{{BASE_IMG_PATH|default(IMAGES_PATH+'/band_base_py')}}"
  - prefix: rst/band-
    collection: true
    base: rst/band-base-py
    path: "{{IMAGES_PATH}}/band_collection"
  - prefix: rst/user-
    collection: true
    base: rst/band-base-py
    path: "{{IMAGES_PATH}}/user"

container_params:
  network: "{{NETWORK|default('custom')}}"
  memory: 367001600 # limit 350mb
  bind_ip: "{{BIND_HOST_IP}}"
  env:
    HOST: '0.0.0.0'
    REDIS_HOST: "{{REDIS_HOST_ISOLATED}}"
    REDIS_DSN: "redis://{{REDIS_HOST_ISOLATED}}:{{REDIS_PORT|default(6379)}}"
    
